### PR TITLE
Update

### PR DESCRIPTION
**Pull request by nd0ut**
Changed rules:
 - Throw error when using `==`
 - Do not throw error when reassign variables like: `acc`, `res`, `req`, `e`.
 - Allow `'x', 'y', 'e', 'i', 'j'` variable names
 - Increase `max-nested-callbacks` from 2 to 3
 - Increase `max-params` from 3 to 4
 - Increase `max-statements` from 10 to 12
 - Allow inline comments because `It is sometimes faster and more obvious to put comments immediately following code` (c) eslint docs
 - Allow `++` in `for` loops
 - Indent 2 spaces inside switch-case
 - Throw error when using undefined variables

Added react rules from https://github.com/uploadcare/webclient-frontend

@Zmoki @bautrukevich 
Do you have any suggestions that should be added to this PR? I mean can you remember any rules that you would like to enable, disable or change?

### CODE REVIEW

**Comment by bautrukevich** [comment]
If we can I want to change the rule for `switch` and add tabulation for `case` as normal.

**Review by Zmoki — APPROVED** [review]

**Comment by bautrukevich** [comment]
And one more thing: "Allow 'x', 'y', 'e', 'i', 'j' variable names" — may be keep only `x, y, i`? I think we don't need a lot of this short variables.

**Comment by bautrukevich** [comment]
e — it's for `event`? j – for iteration? we don't have and maybe don't need to have more than 1 iterator in 1 file.

**Comment by nd0ut** [comment]
@bautrukevich yep, `e` for event, `i,j` for iteration. I would also add `a,b` or even disable this rule at all as [airbnb](https://github.com/airbnb/javascript/pull/569) did.

**Review by bautrukevich — APPROVED** [review]

**Pull request merged**
